txt_box_email='//input[@type="email"]'
txt_box_password='//input[@type="password"]'
btn_login='//button[@type="button"]'
znr_logo='//img[@alt="Logo"]'
nav_button='//span[@class="icon-navigation-icon header__icon"]'
lst_Admin='//li[contains(text(), "Admin")]'
users_option='//span[contains(text(), "Users")]'
btn_new_usr=''
add_new_headder=''
txt_nm=''
txt_email=''
role_select_drop_down=''
btn_create_usr=''
